---
- name: Create directory for docker compose
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'vagrant'
    group: 'vagrant'
    mode: 'u=rwx,g=rx,o=rx'
  loop:
    - '{{ docker_compose_base_path }}'

- name: Template docker-compose file
  ansible.builtin.template:
    src: '{{ docker_compose_file }}'
    dest: '{{ docker_compose_path }}'
    owner: 'vagrant'
    group: 'vagrant'
    mode: 'u=rw,g=r,o=r'

- name: Start docker-compose services so data can be imported
  ansible.builtin.command: 'docker-compose -f {{ docker_compose_path }} up --detach'

- name: Template celery basic systemd service files
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'
  loop:
    - 'celerybeat.service'
    - 'celeryflower.service'

- name: Template systemd service files
  ansible.builtin.template:
    src: 'celery-worker.service'
    dest: '/etc/systemd/system/{{ item.name }}'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'
  loop: '{{ celery_worker_services }}'

- name: Template main config file
  ansible.builtin.template:
    src: 'config.json'
    dest: '{{ app_base_dir }}/leaf-focus-config.json'
    owner: 'vagrant'
    group: 'vagrant'
    mode: 'u=rw,g=r,o=r'

- name: Template bash profile.d file
  ansible.builtin.template:
    src: 'leaf-focus.sh'
    dest: '/etc/profile.d/leaf-focus.sh'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'

- name: Install systemd service files
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable systemd services
  ansible.builtin.systemd:
    enabled: true
    state: 'started'
    name: '{{ item }}'
  loop:
    - 'celerybeat.service'
    - 'celeryflower.service'

- name: Enable systemd services
  ansible.builtin.systemd:
    enabled: true
    state: 'started'
    name: '{{ item.name }}'
  loop: '{{ celery_worker_services }}'
