---
- name: Create required directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'vagrant'
    group: 'vagrant'
    mode: 'u=rwx,g=rwx,o=rx'
  loop:
    - '{{ app_venv_dir }}'

- name: Create the python venv
  become_user: 'vagrant'
  ansible.builtin.command: '/usr/bin/python3.9 -m venv {{ app_venv_dir }}'
  args:
    creates: '{{ app_venv_dir }}/bin/activate'

- name: Update pip in venv
  become_user: 'vagrant'
  ansible.builtin.command: '{{ app_venv_dir }}/bin/python -m pip install -U pip'

- name: Ensure tools for installing venv packages are available
  become_user: 'vagrant'
  ansible.builtin.command: '{{ app_venv_dir }}/bin/pip install -U setuptools wheel'

- name: Install the source into the venv
  become_user: 'vagrant'
  ansible.builtin.command: '{{ app_venv_dir }}/bin/pip install {{ app_source_dir }}'
