version: '3.9'

# ports are in the format HOST:CONTAINER

# service volumes have a short syntax which uses the generic [SOURCE:]TARGET[:MODE] format,
# where SOURCE can be either a host path or volume name.
# TARGET is the container path where the volume is mounted.
# Standard modes are ro for read-only and rw for read-write (default).

services:

  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '{{ port_rabbitmq }}:{{ port_rabbitmq }}'
      - '{{ port_rabbitmq_http }}:{{ port_rabbitmq_http }}'
      - '{{ port_rabbitmq_prom }}:{{ port_rabbitmq_prom }}'
    expose:
      - '{{ port_rabbitmq }}'
      - '{{ port_rabbitmq_http }}'
      - '{{ port_rabbitmq_prom }}'
    restart: 'always'
    hostname: 'rabbitmq'
    logging:
      driver: 'journald'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '{{ app_conf_rabbitmq_file }}:/etc/rabbitmq/enabled_plugins'

  redis:
    image: 'redis:latest'
    ports:
      - '{{ port_redis }}:{{ port_redis }}'
    expose:
      - '{{ port_redis }}'
    restart: 'always'
    logging:
      driver: 'journald'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  redis-ui:
    image: 'rediscommander/redis-commander:latest'
    ports:
      - '{{ port_redis_http }}:{{ port_redis_http }}'
    expose:
      - '{{ port_redis_http }}'
    restart: 'always'
    environment:
      REDIS_HOSTS: 'local:redis:6379'
    logging:
      driver: 'journald'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  prometheus:
    image: 'prom/prometheus:latest'
    ports:
      - '{{ port_prom }}:{{ port_prom }}'
    expose:
      - '{{ port_prom }}'
    restart: 'always'
    logging:
      driver: 'journald'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '{{ app_conf_prom_file }}:/etc/prometheus/prometheus.yml'

  grafana:
    image: 'grafana/grafana:latest'
    ports:
      - '{{ port_grafana }}:{{ port_grafana }}'
    expose:
      - '{{ port_grafana }}'
    restart: 'always'
    logging:
      driver: 'journald'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - 'grafana-storage:/var/lib/grafana'

volumes:
  grafana-storage:
