version: '3.9'

# ports are in the format HOST:CONTAINER

# service volumes have a short syntax which uses the generic [SOURCE:]TARGET[:MODE] format,
# where SOURCE can be either a host path or volume name.
# TARGET is the container path where the volume is mounted.
# Standard modes are ro for read-only and rw for read-write (default).

services:

  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '{{ port_rabbitmq }}:{{ port_rabbitmq }}'
      - '{{ port_rabbitmq_http }}:{{ port_rabbitmq_http }}'
    expose:
      - '{{ port_rabbitmq }}'
      - '{{ port_rabbitmq_http }}'
    restart: 'always'
    hostname: 'rabbitmq'
    logging:
      driver: 'journald'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  redis:
    image: 'redis:latest'
    ports:
      - '{{ port_redis }}:{{ port_redis }}'
    expose:
      - '{{ port_redis }}'
    restart: 'always'
    logging:
      driver: 'journald'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  redis-ui:
    image: 'rediscommander/redis-commander:latest'
    ports:
      - '{{ port_redis_http }}:{{ port_redis_http }}'
    expose:
      - '{{ port_redis_http }}'
    restart: 'always'
    environment:
      REDIS_HOSTS: 'local:redis:6379'
    logging:
      driver: 'journald'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
