---
# rabbit mq
port_rabbitmq: 5672
port_rabbitmq_http: 15672
port_rabbitmq_prom: 15692
rabbitmq_user: 'guest'
rabbitmq_pass: 'guest'

# redis
port_redis: 6379
port_redis_http: 8081

# prometheus
port_prom: 9090
port_grafana: 3000
port_scrapy_prom: 9080

# celery
port_flower: 5555

# apt mirror
ubuntu_apt_source_mirror: 'http://mirror.aarnet.edu.au/pub/ubuntu/archive'
ubuntu_apt_source_mirror_security: 'http://security.ubuntu.com/ubuntu'

# apt sources
ubuntu_package_source_file: '/etc/apt/sources.list'

# dirs
app_base_dir: '/opt/leaf-focus'
app_venv_dir: '{{ app_base_dir }}/venv'
app_source_dir: '{{ app_base_dir }}/source'
app_run_dir: '{{ app_base_dir }}/run'
app_conf_dir: '{{ app_base_dir }}/conf'

app_data_dir: '/mnt/data/processing'
app_items_dir: '/mnt/data/items'
app_cache_dir: '/mnt/data/httpcache'

# config files
app_conf_main_file: '{{ app_conf_dir }}/leaf-focus-config.json'
app_conf_prom_file: '{{ app_conf_dir }}/prometheus.yml'
app_conf_rabbitmq_file: '{{ app_conf_dir }}/rabbitmq-plugins.txt'

# docker
ubuntu_docker_repository: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
ubuntu_docker_repository_key: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
ubuntu_docker_repository_key_url: 'https://download.docker.com/linux/ubuntu/gpg'

# docker compose
docker_compose_bin_file: '/usr/bin/docker-compose'

# check for new versions here: https://github.com/docker/compose/releases
docker_compose_version: '1.29.2'

# docker compose
docker_compose_base_path: '{{ app_base_dir }}/docker-compose'

docker_compose_file: 'docker-compose.yml'
docker_compose_path: '{{ docker_compose_base_path }}/{{ docker_compose_file }}'

# celery
# Absolute path to the 'celery' command
celery_bin: '{{ app_venv_dir }}/bin/celery'
# App instance to use, fully qualified
celery_app: 'leaf_focus.pipeline.app:app'

# celery workers
# ref: https://docs.celeryproject.org/en/stable/reference/cli.html#celery-worker
# ref: https://docs.celeryproject.org/en/stable/reference/celery.bin.multi.html
celery_worker_services:
  - name: 'celery-queue-ocr-prepare.service'
    nodes: 'leaf-focus.node.ocr.prepare.1'
    queues: 'leaf-focus.queue.ocr.prepare'
    opts: '--time-limit=3600 --concurrency=1'

  - name: 'celery-queue-ocr-recognise.service'
    nodes: 'leaf-focus.node.ocr.recognise.1'
    queues: 'leaf-focus.queue.ocr.recognise'
    opts: '--time-limit=3600 --concurrency=1'

  - name: 'celery-queue-work.service'
    nodes: 'leaf-focus.node.work.1 leaf-focus.node.work.2'
    queues: 'leaf-focus.queue.work'
    opts: '--time-limit=3600 --concurrency=2'


# - %n will be replaced with the first part of the nodename.
# - %I will be replaced with the current child process index
#   and is important when using the prefork pool to avoid race conditions.
celery_pid_file: '{{ app_run_dir }}/celery-%%n.pid'
celery_log_file: '{{ app_run_dir }}/celery-%%n%%I.log'
celery_log_level: 'INFO'

#  Celery Beat pid and log files
# ref: https://docs.celeryproject.org/en/stable/reference/cli.html?highlight=beat#celery-beat
celerybeat_pid_file: '{{ app_run_dir }}/celery-beat.pid'
celerybeat_log_file: '{{ app_run_dir }}/celery-beat.log'
celerybeat_log_level: 'INFO'

# celery flower
# ref: https://flower.readthedocs.io/en/latest/man.html
celeryflower_log_level: 'info'

# xpdf
xpdf_gpg_key_file: 'xpdf-gpg-key.txt'
xpdf_gpg_key_id: '97271342'
xpdf_gpg_name: 'xpdf@xpdfreader.com'
xpdf_gpg_fingerprint: 'A56006CA75CF8B13FA2F120DF4825F5397271342'
xpdf_gpg_key_url: 'https://www.xpdfreader.com/gpg-key.txt'
xpdf_dir: 'xpdf-tools-linux-4.03'
xpdf_file_url: 'https://dl.xpdfreader.com/{{ xpdf_dir }}.tar.gz'
xpdf_gpg_url: 'https://dl.xpdfreader.com/{{ xpdf_dir }}.tar.gz.sig'

xpdf_images: '{{ app_base_dir }}/{{ xpdf_dir }}/bin64/pdftopng'
xpdf_text: '{{ app_base_dir }}/{{ xpdf_dir }}/bin64/pdftotext'
xpdf_info: '{{ app_base_dir }}/{{ xpdf_dir }}/bin64/pdfinfo'
