name: "Build and Test"

on:
  push:
    branches:
      - main

jobs:
  build-test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.9'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache python environment
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('requirements.txt') }}

      # generate requirements.txt by running 'poetry export -f requirements.txt -o requirements.txt --dev --without-hashes'
      - name: Install dependencies
        run: |
          pip install --upgrade --upgrade-strategy eager pip
          pip install --upgrade --upgrade-strategy eager setuptools wheel
          pip install -r requirements.txt
          pip install --upgrade --quiet .

      - name: Test with pytest
        run: |
          coverage run -m pytest -m 'not slow and not needs_exe'
          coverage report

      - name: Run linters
        run: |
          flake8 . --count --show-source --statistics
          black --check .

      - name: Check that program can be run
        run: |
          leaf-focus --help
          leaf-focus --version
